version: '2'

services:
  makemap:
    build: ./mapserv
    volumes:
      - ./mapserv/charts/:/home/mapserv/charts/

  mapserver:
    image: camptocamp/mapserver
    volumes:
      - ./mapserv/mapfiles/:/etc/mapserver/
      - ./mapserv/:/home/mapserv/
    ports:
      - "8080:80"
    restart: unless-stopped

  mapproxy:
    image: kartoza/mapproxy
    volumes:
      -  ./mapproxy/chart:/mapproxy
    ports:
      - "8081:8080"
    restart: unless-stopped
